services:
  - type: web
    name: pizzaworld-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: GOOGLE_AI_API_KEY
        sync: false  # This will be set in Render dashboard
      - key: GOOGLE_AI_MODEL
        value: gemini-2.5-flash
      - key: GOOGLE_AI_ENABLED
        value: true 